-- MySQL Script generated by MySQL Workbench
-- vie 02 jun 2017 22:08:38 PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Protectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Protectores` (
  `idProtectores` INT NULL,
  `color` VARCHAR(45) NULL,
  `Tamaño` VARCHAR(20) NULL,
  `Tipo_Material` VARCHAR(45) NULL,
  `Precio` INT(12) NULL,
  `Marca` VARCHAR(5) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`idProtectores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargadores` (
  `idCargadores` INT NULL,
  `color` VARCHAR(15) NULL,
  `tamaño` CHAR(10) NULL,
  `amperaje` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `calidad` VARCHAR(45) NULL,
  `material` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `Protectores_idProtectores` INT NOT NULL,
  PRIMARY KEY (`idCargadores`),
  INDEX `fk_Cargadores_Protectores1_idx` (`Protectores_idProtectores` ASC),
  CONSTRAINT `fk_Cargadores_Protectores1`
    FOREIGN KEY (`Protectores_idProtectores`)
    REFERENCES `mydb`.`Protectores` (`idProtectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Memorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Memorias` (
  `idMemorias` INT NULL,
  `capacidad` INT(3) NULL,
  `calidad` VARCHAR(20) NULL,
  `Marca` VARCHAR(45) NULL,
  PRIMARY KEY (`idMemorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Accesorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Accesorios` (
  `idTipo_Accesorios` INT NULL,
  `Tipo_accesorio` VARCHAR(45) NULL,
  `Precio` DECIMAL(1000) NULL,
  `Color` VARCHAR(45) NULL,
  `Tamaño` VARCHAR(45) NULL,
  `calidad` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Genero` CHAR(10) NULL,
  `Tipo_Material` VARCHAR(45) NULL,
  `Descripcion` TEXT(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Protectores_idProtectores` INT NOT NULL,
  `Cargadores_idCargadores` INT NOT NULL,
  `Memorias_idMemorias` INT NOT NULL,
  PRIMARY KEY (`idTipo_Accesorios`),
  INDEX `fk_Tipo_Accesorios_Protectores1_idx` (`Protectores_idProtectores` ASC),
  INDEX `fk_Tipo_Accesorios_Cargadores1_idx` (`Cargadores_idCargadores` ASC),
  INDEX `fk_Tipo_Accesorios_Memorias1_idx` (`Memorias_idMemorias` ASC),
  CONSTRAINT `fk_Tipo_Accesorios_Protectores1`
    FOREIGN KEY (`Protectores_idProtectores`)
    REFERENCES `mydb`.`Protectores` (`idProtectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo_Accesorios_Cargadores1`
    FOREIGN KEY (`Cargadores_idCargadores`)
    REFERENCES `mydb`.`Cargadores` (`idCargadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo_Accesorios_Memorias1`
    FOREIGN KEY (`Memorias_idMemorias`)
    REFERENCES `mydb`.`Memorias` (`idMemorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marcas_Telefonos_En_Ensenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marcas_Telefonos_En_Ensenda` (
  `idMarca` INT NULL,
  `id_modelo` INT NULL,
  `Color` VARCHAR(45) NULL,
  `Tamaño` VARCHAR(45) NULL,
  `Caracteristicas` TEXT(30) NULL,
  `Tipo_Accesorios_idTipo_Accesorios` INT NOT NULL,
  `Tipo_Accesorios_Tipo_Accesorios_idTipo_Accesorios` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marcas_Telefonos_En_Ensenda_Tipo_Accesorios1_idx` (`Tipo_Accesorios_idTipo_Accesorios` ASC, `Tipo_Accesorios_Tipo_Accesorios_idTipo_Accesorios` ASC),
  CONSTRAINT `fk_Marcas_Telefonos_En_Ensenda_Tipo_Accesorios1`
    FOREIGN KEY (`Tipo_Accesorios_idTipo_Accesorios`)
    REFERENCES `mydb`.`Tipo_Accesorios` (`idTipo_Accesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NULL,
  `Tipo_cliente` VARCHAR(20) NULL,
  `Nombre_cliente` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Comunidad` CHAR(10) NULL,
  `Telefono` TINYINT(4) NULL,
  `Fecha_Ultima_Visita` DATE NULL,
  `Tipo_Accesorios_idTipo_Accesorios` INT NOT NULL,
  PRIMARY KEY (`idclientes`),
  INDEX `fk_clientes_Tipo_Accesorios1_idx` (`Tipo_Accesorios_idTipo_Accesorios` ASC),
  CONSTRAINT `fk_clientes_Tipo_Accesorios1`
    FOREIGN KEY (`Tipo_Accesorios_idTipo_Accesorios`)
    REFERENCES `mydb`.`Tipo_Accesorios` (`idTipo_Accesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `Nombre` CHAR(20) NULL,
  `telefono` INT(12) NULL,
  `Ultima_Visita` DATE NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Baterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Baterias` (
  `idBaterias` INT NOT NULL,
  `Color` VARCHAR(45) NULL,
  `Tamaño` VARCHAR(20) NULL,
  `Marca` VARCHAR(25) NULL,
  `Modelo` VARCHAR(20) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Cargadores_idCargadores` INT NOT NULL,
  `Tipo_Accesorios_idTipo_Accesorios` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idBaterias`),
  INDEX `fk_Baterias_Cargadores1_idx` (`Cargadores_idCargadores` ASC),
  INDEX `fk_Baterias_Tipo_Accesorios1_idx` (`Tipo_Accesorios_idTipo_Accesorios` ASC),
  INDEX `fk_Baterias_Proveedor1_idx` (`Proveedor_idProveedor` ASC),
  CONSTRAINT `fk_Baterias_Cargadores1`
    FOREIGN KEY (`Cargadores_idCargadores`)
    REFERENCES `mydb`.`Cargadores` (`idCargadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Baterias_Tipo_Accesorios1`
    FOREIGN KEY (`Tipo_Accesorios_idTipo_Accesorios`)
    REFERENCES `mydb`.`Tipo_Accesorios` (`idTipo_Accesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Baterias_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro` (
  `id_Usuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Correo_Electronico` VARCHAR(45) NULL,
  `Tipo_Usuario` VARCHAR(20) NULL,
  `Fecha_Registro` DATE NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  INDEX `fk_Registro_clientes1_idx` (`clientes_idclientes` ASC),
  CONSTRAINT `fk_Registro_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `mydb`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
